apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: innoveo-demo
  labels:
    app: innoveo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: innoveo-frontend
  template:
    metadata:
      labels:
        app: innoveo-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/innoveo/demo-frontend:latest
          ports:
            - containerPort: 4173
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: innoveo-config
                  key: API_BASE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
