apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: innoveo-demo
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: innoveo
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
    exporters:
      logging:
        loglevel: warn
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
